# Generated 2023-03-28 from:
# /root/projects/separation/speechbrain/recipes/LibriMix/separation/hparams/sepformer-libri2mix.yaml
# yamllint disable
# ################################
# Model: SepFormer for source separation
# https://arxiv.org/abs/2010.13154
# Dataset : Libri2mix
# ################################

# Experiment params
auto_mix_prec: true # Set it to True for mixed precision
test_only: true
num_spks: 2
noprogressbar: false
save_audio: true # Save estimated sources on disk
sample_rate: 8000

# Training parameters
N_epochs: 30
batch_size: 1
lr: 0.00015
clip_grad_norm: 5
loss_upper_lim: 999999 # this is the upper limit for an acceptable loss
# if True, the training sequences are cut to a specified length
limit_training_signal_len: true
# this is the length of sequences if we choose to limit
# the signal length of training sequences
training_signal_len: 8000

# Set it to True to dynamically create mixtures at training time
dynamic_mixing: false
use_wham_noise: false

# Parameters for data augmentation
use_wavedrop: false
use_speedperturb: true
use_rand_shift: false
min_shift: -8000
max_shift: 8000

speedperturb: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  perturb_prob: 1.0
  drop_freq_prob: 0.0
  drop_chunk_prob: 0.0
  sample_rate: 8000
  speeds: [95, 100, 105]

wavedrop: !new:speechbrain.lobes.augment.TimeDomainSpecAugment
  perturb_prob: 0.0
  drop_freq_prob: 1.0
  drop_chunk_prob: 1.0
  sample_rate: 8000

# loss thresholding -- this thresholds the training loss
threshold_byloss: true
threshold: -30

# Encoder parameters
N_encoder_out: 256
out_channels: 256
kernel_size: 16
kernel_stride: 8
d_ffn: 1024

# Dataloader options
dataloader_opts:
  batch_size: 1
  num_workers: 4

# Specifying the network
Encoder: !new:speechbrain.lobes.models.dual_path.Encoder &id003
  kernel_size: 16
  out_channels: 256

SBtfintra: !new:speechbrain.lobes.models.dual_path.SBTransformerBlock &id001
  num_layers: 8
  d_model: 256
  nhead: 8
  d_ffn: 1024
  dropout: 0
  use_positional_encoding: true
  norm_before: true

SBtfinter: !new:speechbrain.lobes.models.dual_path.SBTransformerBlock &id002
  num_layers: 8
  d_model: 256
  nhead: 8
  d_ffn: 1024
  dropout: 0
  use_positional_encoding: true
  norm_before: true

MaskNet: !new:speechbrain.lobes.models.dual_path.Dual_Path_Model &id005
  num_spks: 2
  in_channels: 256
  out_channels: 256
  num_layers: 2
  K: 250
  intra_model: *id001
  inter_model: *id002
  norm: ln
  linear_layer_after_inter_intra: false
  skip_around_intra: true

Decoder: !new:speechbrain.lobes.models.dual_path.Decoder &id004
  in_channels: 256
  out_channels: 1
  kernel_size: 16
  stride: 8
  bias: false

optimizer: !name:torch.optim.Adam
  lr: 0.00015
  weight_decay: 0

loss: !name:speechbrain.nnet.losses.get_si_snr_with_pitwrapper

lr_scheduler: !new:speechbrain.nnet.schedulers.ReduceLROnPlateau
  factor: 0.5
  patience: 2
  dont_halve_until_epoch: 5

epoch_counter:
  !new:speechbrain.utils.epoch_loop.EpochCounter &id006 # lr_scheduler: !ref <lr_scheduler>

  limit: 30

modules:
  encoder: *id003
  decoder: *id004
  masknet: *id005


# If you do not want to use the pretrained separator you can simply delete pretrained_separator field.
pretrained_separator: !new:speechbrain.utils.parameter_transfer.Pretrainer
  loadables:
    encoder: *id003
    decoder: *id004
    masknet: *id005
  paths:
    encoder: util/models/speech_separation/model/encoder.ckpt
    decoder: util/models/speech_separation/model/decoder.ckpt
    masknet: util/models/speech_separation/model/masknet.ckpt
